[package]
name = "phorg"
version = "0.3.0"
description = "Photo files organizer"
repository = "https://github.com/xandkar/phorg"
keywords = ["photo", "organizer", "exif"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.7", features = ["derive"] }
kamadak-exif = "0.5.5"
thiserror = "1.0.61"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
