[package]
name = "phorg"
description = "Photo files organizer"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.7", features = ["derive"] }
kamadak-exif = "0.5.5"
